name: chita_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  another_telephony: ^0.4.1
  http: ^1.2.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  shared_preferences: ^2.3.2
  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  connectivity_plus: ^6.0.5
  url_launcher: ^6.3.0
  google_maps_flutter: ^2.13.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: any
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
